### ISSUE TITLE
Upgrade 5.1 to 5.2 issue

### ISSUE THREAD

**Issue by gpfti** [cytech/BillingTrack#13]
Hi cytech,

After runnping composer update I finally get these error messages at the end of the update process:

Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
PHP Fatal error:  Declaration of BT\Exceptions\Handler::report(Throwable $exception) must be compatible with Illuminate\Foundation\Exceptions\Handler::report(Exception $e) in /var/www/billingtrack/app/Exceptions/Handler.php on line 8
PHP Fatal error:  Uncaught ReflectionException: Class BT\Exceptions\Handler does not exist in /var/www/billingtrack/vendor/laravel/framework/src/Illuminate/Container/Container.php:803
Stack trace:
#0 /var/www/billingtrack/vendor/laravel/framework/src/Illuminate/Container/Container.php(803): ReflectionClass->__construct('BT\\Exceptions\\H...')
#1 /var/www/billingtrack/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\Container\Container->build('BT\\Exceptions\\H...')
#2 /var/www/billingtrack/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\Container\Container->resolve('BT\\Exceptions\\H...', Array, false)
#3 /var/www/billingtrack/vendor/laravel/framework/src/Illuminate/Container/Container.php(265): Illuminate\Foundation\Application->resolve('BT\\Exceptions\\H...', Array, false)
#4 /var/www/billingtrack/vendor/laravel/framework/src/Illuminate/Container/Container.php(799): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(BT\Application), Array) in /var/www/billingtrack/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 805
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255

I could run YOUR_BILLINGTRACK_WEBSITE/setup
Database was updated, I could find data in the dashboard, but I couldn't list or access to any invoice, budget, etc. 

Regards,

Guillermo

**Comment by cytech** [comment]
it sounds like maybe
app/Exceptions/Handler.php
did not get updated properly.
can you verify that app/Exceptions/Handler.php on your install matches the one in the master repo?

**Comment by gpfti** [comment]
Hi cytech,
Is strange because I did download the new version, nenamed app and public folders and unzipped new 5.2 app and public folders before running composer update.

I will retry it next Thursday again with your instructions.

Thank you very much,

Guillermo
