### ISSUE TITLE
Commercial side

### ISSUE THREAD

**Issue by sergiyMaster** [cytech/BillingTrack#27]
Hi there
I'm new in a commercial questions. But i have few.
Do you give access to the code under the licence? If yes, cannot find one.
What is the business model for provided code if you ever think about it.

Regards,
Sergiy

**Comment by nickbe** [comment]
No detailled decision have been made about the commercial license at this time. However we will look very closely at the difference between the needs of small workgroups and those of a corporate like environment. As soon as the license becomes clear there will be an announcement.

**Comment by sergiyMaster** [comment]
Dear Nick
Hope you are well.
Thanks for your reply.

What business model will you use for your business?
I'm thinking of pushing a product on the github and don't know what is the
right way to make money from it.


Regards,
Sergiy Safronov
