### ISSUE TITLE
Company Email Issues

### ISSUE THREAD

**Issue by Kwaku-Ananse** [cytech/BillingTrack#48]
Hello, my second time trying this nice web app and I noticed that, when you add any company profile with their company name and email address, when you create an invoice under that company's name, their unique or respective email address does not appear on the invoice, instead, the admin user email is what appears on the invoice and it applies any other company you add. 

please look into it. I was expecting it to have been reported by other users. Each company profile added has an email field and so that email should be appearing on their invoices to their clients. showing the main admin user email on all invoices doesnt look professional and defeats the purpose of having multi tenants.

VAT NUMBER does not APPEAR ON INVOICE....I input a VAT number in the field but when I go to view invoice, it is not on there at all

I haven't tested other functions but I expect I can create a user account for each added company and when they login, they will be directly logged into their own account, meaning they will only see their company assigned to the logged in use and wont see other companies. only the admin account can see all companies in dashboard and other users only see what is assigned to them

this a simple app and well structured. GOOD JOB!

**Comment by Kwaku-Ananse** [comment]
no response?

**Comment by cytech** [comment]
> when you create an invoice under that company's name, their unique or respective email address does not appear on the invoice, instead, the admin user email is what appears on the invoice and it applies any other company you add.

feature request

> VAT NUMBER does not APPEAR ON INVOICE

feature request

>  I expect I can create a user account for each added company and when they login, they will be directly logged into their own account

that is not the case. the app is structured for a single company/freelancer. the company profile is just a means to allow the freelancer to bill under different company names.

**Comment by Kwaku-Ananse** [comment]
Well understood. not a bad thing at all. can you fix the extra 00 added to item quantities please.....example, 1 becomes 1.00 on the invoice. quantity should be 1 and not not 1.00

**Comment by Kwaku-Ananse** [comment]
Am going to re-install the app again. last time i tried, I gave up after not being able to add new invoice etc....the add new tap wont respond only if i was logged in at localhost and not over https. I will try again and give you more feed back

**Comment by cytech** [comment]
Please provide your feedback in the Discussions area of this repository.
Only use issues for reporting reproducible bugs using the new issue template
