### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Pedestrian80** [cytech/BillingTrack#5]
Can‘t install billingtrack, because billingtrack/setup don‘t exist. Please to add the Installdoku.

**Comment by cytech** [comment]
http://YOUR_BILLINGTRACK_WEBSITE/setup

**Comment by Pedestrian80** [comment]
I have installed BillingTrack on Xampp. Composer installation, artisan key in .env worked. But the setup does not want to start. I only get the license agreement, which I confirm. After that I get the following message:
"The following prerequisites need to be resolved before installation can continue: It appears app/config/database.php has not yet been configured."

The database settings were already stored in the .env. What could it be?
Thank so lot Matthias

**Comment by cytech** [comment]
have you created the mysql database and given it the appropriate permissions?

**Comment by Pedestrian80** [comment]
yes, the databasename is billing, user is root without password, all privileges allowed, database is utf8mb4_unicode_ci

**Comment by cytech** [comment]
you should create a billingtrack user and password with permissions for your 'billing' database (not root with no password).
then enter that information in .env
DB_HOST= YOURHOST
DB_DATABASE= billing
DB_USERNAME= YOURBILLINGTRACKUSER
DB_PASSWORD= YOURBILLINGTRACKUSERPASSWORD

**Comment by Pedestrian80** [comment]
OK, now I get the following message: "This step will install and upgrade your database tables. This step may take a few moments to complete. Continue" But nothing happens. Is that normal that no logo is displayed in the setup and apparently no css is loaded?

Should be ran „php artisan migrate“, „php artisan db:seed“ and „php artisan serve" ?

**Comment by cytech** [comment]
sometimes i think you have to hit continue again

**Comment by Pedestrian80** [comment]
I just started over again. Unfortunately, I can not continue with the setup. A button is not available.

![2019-06-01_1](https://user-images.githubusercontent.com/51230727/58749427-4afba280-8486-11e9-8edd-20ff404a0a07.png)

**Comment by cytech** [comment]
I am not sure what is happening.
If you are starting from scratch, drop the billing schema and re-create it.
Then run setup again

**Comment by cytech** [comment]
also make sure website permissions are good and open permissions on storage and bootstrap/cache dirs.
sudo chmod -R 777 storage
sudo chmod -R 777 bootstrap/cache
you can also try:
php artisan clear-compiled
php artisan view:clear
php artisan cache:clear
php artisan config:clear
composer dump-autoload

**Comment by Pedestrian80** [comment]
Thanks for the tips. I will try again this weekend.

**Comment by molazabala** [comment]
> debe crear un usuario y una contraseña de billingtrack con permisos para su base de datos de "facturación" (no root sin contraseña). 
> luego ingrese esa información en .env 
> DB_HOST = YOURHOST 
> DB_DATABASE = billing 
> DB_USERNAME = YOURBILLINGTRACKUSER 
> DB_PASSWORD = YOURBILLINGTRACKUSERPASSWORD

cytech
- Eh carried out the following steps from 1 to 7 without problems
- Additional create an INV_DB database with (user: userinv) and (password: Ain285-)
Then I open my browser and open the page http://localhost/setup/ and I get "file or directory not found."
I leave the key that generates me in .env:
APP_KEY = base64: dRtP0ks24dOmfCSwbdb4IpGSOfIX5yMxcjt0MPrtcY0 =
I would appreciate your contribution

**Comment by vertexlex** [comment]
Same trouble. 
molazabala, any luck?

**Comment by OlooFC** [comment]
trying to create a seeder class for initial login to the system but getting **`Target class [Database\Seeders\UserSeeder​] does not exist`**
